### ISSUE TITLE
Question about battery usage

### ISSUE THREAD

**Issue by chmac** [zaneclaes/van-home-assistant-config#1]
I read your article about bringing the smart home into your van. Sounds very cool. Especially the stuff about motion detection and so on. My van was recently broken into, quite expensive, a lot of valuables were stolen, and now I'm thinking about whether I can bring some open source tech bear in order to upgrade my security. Thanks for the article, it's a big help to see what's possible.

One question, how much power does your setup use? I don't have an onboard battery in the van, I use portable power stations (which were stolen, one downside of them being portable. 😢 ). I'm wondering how long the whole system would operate without me needing to recharge it...

**Comment by zaneclaes** [comment]
Hey! Sorry to hear about the theft.

There are a lot of variables at play here. I have, at times, used a full Linux machine in the van (with a DC power supply), which idles at around 50W and peaks around 110W. However, a Raspberry Pi (or even Pi Zero) can operate at a fraction of this. If power consumption is a real concern, a Pi Zero is the biggest win (but also the slowest device, perhaps frustratingly so). That said, even a standard Pi peaks at mere `5.1V * 3A = 15.5W` (based on the official power adapters).

This covers the computer and camera, but you also need to consider any networking gear necessary to communicate alerts to your mobile device. If you have Starlink running, for example, that's a huge draw on its own (especially if its using the heater to melt snow). Ours has averaged 75W over the last few days. But a simple Mifi-like device (Verizon Jetpack or whatever), based on the specs, is rated around a mere 1W (4.4 Ah battery * 5v = 22 kWh / 24h rated use time = 1W).

All that to say, a reasonable Mifi + RPi camera setup should not exceed something like 20W max.

Assuming you have 12V batteries, then running this system for 24 hours would require a maximum of a 4 Ah battery. Hopefully this leaves you lots of headroom for re-charching, long periods away, etc.

**Comment by chmac** [comment]
@zaneclaes Yeah, the worst about the theft is I keep finding stuff that I had forgotten was in the van, and now it ain't. That's life. :-\

Thanks for the power info. Yeah, I was doing some similar calculations. I don't have solar and I don't have 12V batteries, only a 1.2kWh anker power station and a few smaller ones. Plus, I often leave the van for 4-6 weeks at a stretch. So ideally I'm looking for a setup which will run that long without needing any input or charge. Even 20W will become pretty heavy over a week, never mind a month!
